- app/vues/kit/nav-principale.pug
… pour satisfaire la vérification du DSFR dans Dashlord.
> Ajoute le header DSFR

- .github/workflows/deploiement.yml
- .github/workflows/integration-continue.yml
- back/eslint.config.mts
- back/package.json
- back/src/api/dsc.ts
- package-lock.json
- package.json
...afin de lancer les tests lors de l'ouverture d'une Pull request
> Configure l'intégration continue

- .github/workflows/deploiement.yml
...suite à une erreur de syntaxe
> Corrige le déploiement

- back/.env.template
- back/package.json
- back/pages/apres-authentification.html
- back/src/api/adaptateurJWT.ts
- back/src/api/dsc.ts
- back/src/api/oidc/adaptateurOIDC.ts
- back/src/api/oidc/ressourceApresAuthentificationOIDC.ts
- back/src/api/oidc/ressourceConnexionOIDC.ts
- back/src/infra/adaptateurEnvironnement.ts
- back/src/infra/adaptateurHachage.ts
- back/src/infra/entrepotUtilisateurPostgres.ts
- back/src/metier/entrepotUtilisateur.ts
- back/src/metier/utilisateur.ts
- back/src/serveur.ts
- back/tests/api/cookie.ts
- back/tests/api/dsc.spec.ts
- back/tests/api/fauxObjets.ts
- back/tests/api/oidc/__snapshots__/ressourceApresAuthentificationOIDC.spec.ts.snap
- back/tests/api/oidc/ressourceApresAuthentificationOIDC.spec.ts
- back/tests/api/oidc/ressourceConnexionOIDC.spec.ts
- back/tests/infra/adaptateurEnvironnement.spec.ts
- back/tests/infra/adaptateurHachage.spec.ts
- back/tests/infra/entrepotMemoire.ts
- back/tests/infra/entrepotUtilisateurMemoire.ts
- back/todo.md
- package-lock.json
Ajoute les routes suivantes :
- /oidc/connexion pour initialiser la cinématique d’authentification
- /oidc/apres-authentification pour terminer l’authentification et vérifier si l’utilisateur est connecté ou pas
Pour ces deux routes, on s’appuie sur les mêmes mécanismes que MesServicesCyber
> [PROCONNECT] Ajoute la cinématique d’authentification

- .gitignore
- README.md
- back/.env.template
- back/knexfile.ts
- back/migrations/20250901125832_creerTableUtilisateurs.ts
- back/package.json
- docker-compose.yml
- docker-entrypoint-initdb.d/initialise.sql
- package-lock.json
- package.json
Introduit la bibliothèque knex et sa configuration, et met à jour les scripts pour le développement local
> [BDD] Initialise la base de données

- back/src/infra/entrepotRessourcesCyberGrist.ts
- back/src/infra/entrepotRessourcesCyberStatique.ts
- back/src/metier/ressourceCyber.ts
- back/tests/api/ressourceRessourcesCyber.spec.ts
- back/tests/infra/entrepotRessourcesCyberGrist.spec.ts
- front/src/Catalogue.svelte
- front/src/ressourceCyber.ts
- front/src/stores/rechercheParNiveau.store.ts
- front/src/stores/ressourcesCyberFiltrees.store.ts
- front/tests/constructeurRessourceCyber.ts
- front/tests/stores/rechercheParNiveau.store.spec.ts
- front/tests/stores/ressourcesCyberFiltrees.store.spec.ts
> Récupère et affiche les niveaux et filtre les ressources Cyber en fonction

- back/src/infra/entrepotRessourcesCyberGrist.ts
- back/src/infra/entrepotRessourcesCyberStatique.ts
- back/src/metier/ressourceCyber.ts
- back/tests/api/ressourceRessourcesCyber.spec.ts
- back/tests/infra/entrepotRessourcesCyberGrist.spec.ts
- front/src/Catalogue.svelte
- front/src/ressourceCyber.ts
- front/src/stores/rechercheParBesoin.store.ts
- front/src/stores/ressourcesCyberFiltrees.store.ts
- front/tests/constructeurRessourceCyber.ts
- front/tests/stores/rechercheParBesoin.store.spec.ts
- front/tests/stores/ressourcesCyberFiltrees.store.spec.ts
> Récupère et affiche les besoins et filtre les ressources Cyber en fonction

- front/src/Catalogue.svelte
- front/src/FiltreBesoin.svelte
- front/src/FiltreNiveau.svelte
- front/src/FiltreSelection.svelte
- front/src/FiltreThematique.svelte
- front/src/FiltreType.svelte
... chacun dans son propre composant svelte
> [SOIN] Extrais les filtres du catalogue

- back/src/api/dsc.ts
- back/src/api/oidc/ressourceApresDeconnexionOIDC.ts
- back/src/api/oidc/ressourceDeconnexionOIDC.ts
- back/tests/api/oidc/ressourceApresDeconnexionOIDC.spec.ts
- back/tests/api/oidc/ressourceDeconnexionOIDC.spec.ts
- front/public/index.html
- front/src/ZoneIdentification.svelte
- front/src/index.ts
...sur la page d'accueil.
On propose aussi le lien de connexion systématiquement pour le moment. La détection d'un profil connecté se fera ultérieurement
> Propose le lien de déconnexion

- front/src/Catalogue.svelte
... plus finement avec un état de chargement et un état d'erreur
> Gère le chargement des ressources

- .pre-commit-config.yaml
Suite aux erreurs rencontrées sous Linux/Ubuntu
> [TECH] Modifie la configuration eslint

- back/src/api/dsc.ts
- back/src/api/moteurDeRendu.ts
- back/src/api/ressourcesApi.ts
- back/src/api/ressourcesOidc.ts
- back/src/api/ressourcesPages.ts
- back/tests/api/dsc.spec.ts
On a extrait l'enregistrement des routes et des ressources dans des fichiers distincts car on trouvé que `dsc.ts` grossi très vite...
> Corrige le moteur de rendu et améliore l'enregistrement des routes

- back/migrations/20250915125920_ajouteColonneEnseignantAJeu.ts
- back/src/api/middleware.ts
- back/src/api/ressourceJeux.ts
- back/src/express.d.ts
- back/src/infra/entrepotJeuxPostgres.ts
- back/src/metier/jeu.ts
- back/src/serveur.ts
- back/tests/api/fauxObjets.ts
- back/tests/api/middleware.spec.ts
- back/tests/api/objetsPretsALEmploi.ts
- back/tests/api/ressourceJeux.spec.ts
- back/tests/api/ressourceProfil.spec.ts
> [DEPOSE-JEU] Associe le jeu à l'utilisateur connecté

- back/vues/base.pug
- front/src/FiltreNiveau.svelte
- front/src/FiltrePublicCible.svelte
- front/src/FiltreThematique.svelte
- front/src/FiltreType.svelte
- front/src/RechercheTextuelle.svelte
... pour les filtres du catalogue
> [DSFR] Utilise les composants DSFR

- front/package.json
- front/src/jeux/FormulaireNouveauJeu.svelte
- front/tests/jeux/FormulaireNouveauJeu.spec.ts
- front/tests/shadow-dom-utilitaires.ts
- front/tests/vitest-setup.ts
- front/vitest-setup.ts
- front/vitest.config.ts
- package-lock.json
...ce qui implique d'adapter nos méthodes de test a des composants se rendant dans un shadow dom
> Utilise le bouton dsfr

- .github/workflows/deploiement.yml
> [CORRECTION] Corrige l’action github pour le déploiement

- back/src/api/middleware.ts
...afin que les images dans les styles provenant du DSFR s’affichent correctement
> Corrige les problèmes liés au Content Security Policy

- front/src/jeux/FormulaireNouveauJeu/EtapeInformationsGenerales.svelte
- front/src/jeux/FormulaireNouveauJeu/EtapePresentation.svelte
> Corrige la disparition du placeholder

- back/src/metier/referentiels/disciplines.ts
- front/src/jeux/FormulaireNouveauJeu/EtapeInformationsGenerales.svelte
> Mets à jour les disciplines

- back/vues/entete.pug
- front/src/_standard.scss
- front/src/jeux/MesJeux.svelte
- front/statique/icons/system/question-answer-line.svg
- supprime les entrées de navigation inutiles
- mets en forme la page `Mes jeux` lorsqu’il y a des jeux
- mets en forme la page `Mes jeux` lorsqu’il n’y a aucun jeu
> Apporte des corrections visuelles
